# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 20:55
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shandianbao', '0002_sdbpos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDBFenRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_point', models.CharField(choices=[(b'0.55', '0.55'), (b'0.555', '0.555'), (b'0.56', '0.56'), (b'0.565', '0.565'), (b'0.57', '0.57'), (b'0.575', '0.575'), (b'0.58', '0.58'), (b'0.585', '0.585'), (b'0.59', '0.59'), (b'0.595', '0.595'), (b'0.6', '0.6'), (b'0.605', '0.605'), (b'0.61', '0.61'), (b'0.615', '0.615'), (b'0.62', '0.62'), (b'0.625', '0.625'), (b'0.63', '0.63'), (b'0.635', '0.635'), (b'0.64', '0.64'), (b'0.645', '0.645'), (b'0.65', '0.65'), (b'0.655', '0.655'), (b'0.66', '0.66'), (b'0.665', '0.665'), (b'0.67', '0.67'), (b'0.675', '0.675'), (b'0.68', '0.68'), (b'0.685', '0.685'), (b'0.69', '0.69'), (b'0.695', '0.695'), (b'0.7', '0.7'), (b'0.705', '0.705'), (b'0.71', '0.71'), (b'0.715', '0.715'), (b'0.72', '0.72')], max_length=50, verbose_name='\u786c\u4ef6\u8d39\u7387')),
                ('point', models.CharField(choices=[(b'0.5', '0.5'), (b'0.505', '0.505'), (b'0.51', '0.51'), (b'0.515', '0.515'), (b'0.52', '0.52'), (b'0.525', '0.525'), (b'0.53', '0.53'), (b'0.535', '0.535'), (b'0.54', '0.54'), (b'0.545', '0.545'), (b'0.55', '0.55'), (b'0.555', '0.555'), (b'0.56', '0.56'), (b'0.565', '0.565'), (b'0.57', '0.57'), (b'0.575', '0.575'), (b'0.58', '0.58'), (b'0.585', '0.585'), (b'0.59', '0.59'), (b'0.595', '0.595'), (b'0.6', '0.6'), (b'0.605', '0.605'), (b'0.61', '0.61'), (b'0.615', '0.615'), (b'0.62', '0.62'), (b'0.625', '0.625'), (b'0.63', '0.63'), (b'0.635', '0.635'), (b'0.64', '0.64'), (b'0.645', '0.645'), (b'0.65', '0.65'), (b'0.655', '0.655'), (b'0.66', '0.66'), (b'0.665', '0.665'), (b'0.67', '0.67'), (b'0.675', '0.675'), (b'0.68', '0.68'), (b'0.685', '0.685'), (b'0.69', '0.69'), (b'0.695', '0.695'), (b'0.7', '0.7'), (b'0.705', '0.705'), (b'0.71', '0.71'), (b'0.715', '0.715'), (b'0.72', '0.72')], max_length=50, verbose_name='\u4ee3\u7406\u8d39\u7387')),
                ('profit', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='\u5206\u6da6\u6bd4\u4f8b')),
                ('tax', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(30)], verbose_name='\u7a0e\u70b9\u6bd4\u4f8b')),
                ('message', models.TextField(blank=True, verbose_name='\u8bf4\u660e')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'sdb_fenrun',
                'verbose_name': '\u95ea\u7535\u5b9d\u5206\u6da6',
                'verbose_name_plural': '\u95ea\u7535\u5b9d\u5206\u6da6',
            },
        ),
    ]
