# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shandianbao', '0007_auto_20181008_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sdbfenrun',
            options={'verbose_name': '\u7528\u6237\u5206\u6da6', 'verbose_name_plural': '\u7528\u6237\u5206\u6da6'},
        ),
        migrations.AlterModelOptions(
            name='sdbpos',
            options={'verbose_name': '\u7528\u6237\u7ec8\u7aef', 'verbose_name_plural': '\u7528\u6237\u7ec8\u7aef'},
        ),
        migrations.AlterModelOptions(
            name='sdbuserrmb',
            options={'ordering': ['-rmb', '-child_rmb'], 'verbose_name': '\u7528\u6237\u91d1\u94b1', 'verbose_name_plural': '\u7528\u6237\u91d1\u94b1'},
        ),
        migrations.AddField(
            model_name='sdbfenrun',
            name='fanxian_rmb',
            field=models.CharField(choices=[(b'120', b'120'), (b'130', b'130'), (b'140', b'140'), (b'150', b'150'), (b'160', b'160'), (b'170', b'170'), (b'180', b'180'), (b'190', b'190'), (b'200', b'200')], default=b'120', max_length=50, verbose_name='\u8fd4\u73b0\u91d1\u989d\uff08\u5143\uff09'),
        ),
        migrations.AddField(
            model_name='sdbuserrmb',
            name='fanxian_child_rmb',
            field=models.IntegerField(default=0, verbose_name='\u63a8\u8350\u9996\u5237\u8fd4\u73b0'),
        ),
        migrations.AddField(
            model_name='sdbuserrmb',
            name='fanxian_rmb',
            field=models.IntegerField(default=0, verbose_name='\u9996\u5237\u8fd4\u73b0'),
        ),
        migrations.AlterField(
            model_name='sdbchildoneprofit',
            name='point_type',
            field=models.CharField(choices=[(b'DAI', '\u8d37\u8bb0\u5361'), (b'JIE', '\u501f\u8bb0\u5361'), (b'YUN', '\u4e91\u95ea\u4ed8'), (b'YIN', '\u94f6\u8054\u5feb\u6377'), (b'WX', '\u5fae\u4fe1\u652f\u4ed8\u5b9d'), (b'FX', '\u8fd4\u73b0')], max_length=10, verbose_name='\u8d39\u7387\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='sdbchildthreeprofit',
            name='point_type',
            field=models.CharField(choices=[(b'DAI', '\u8d37\u8bb0\u5361'), (b'JIE', '\u501f\u8bb0\u5361'), (b'YUN', '\u4e91\u95ea\u4ed8'), (b'YIN', '\u94f6\u8054\u5feb\u6377'), (b'WX', '\u5fae\u4fe1\u652f\u4ed8\u5b9d'), (b'FX', '\u8fd4\u73b0')], max_length=10, verbose_name='\u8d39\u7387\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='sdbchildtwoprofit',
            name='point_type',
            field=models.CharField(choices=[(b'DAI', '\u8d37\u8bb0\u5361'), (b'JIE', '\u501f\u8bb0\u5361'), (b'YUN', '\u4e91\u95ea\u4ed8'), (b'YIN', '\u94f6\u8054\u5feb\u6377'), (b'WX', '\u5fae\u4fe1\u652f\u4ed8\u5b9d'), (b'FX', '\u8fd4\u73b0')], max_length=10, verbose_name='\u8d39\u7387\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='sdbprofit',
            name='point_type',
            field=models.CharField(choices=[(b'DAI', '\u8d37\u8bb0\u5361'), (b'JIE', '\u501f\u8bb0\u5361'), (b'YUN', '\u4e91\u95ea\u4ed8'), (b'YIN', '\u94f6\u8054\u5feb\u6377'), (b'WX', '\u5fae\u4fe1\u652f\u4ed8\u5b9d'), (b'FX', '\u8fd4\u73b0')], max_length=10, verbose_name='\u8d39\u7387\u7c7b\u578b'),
        ),
    ]
