# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='\u624b\u673a')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('sex', models.CharField(choices=[(b'F', '\u5973'), (b'M', '\u7537'), (b'O', '\u5176\u4ed6')], max_length=1, verbose_name='\u6027\u522b')),
                ('is_vip', models.BooleanField(default=False, verbose_name='\u662f\u5426VIP')),
                ('code', models.CharField(max_length=36, unique=True, verbose_name='\u9080\u8bf7\u7801')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='\u4e0a\u5bb6')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vuser_profile',
                'verbose_name': '\u7528\u6237\u5c5e\u6027',
                'verbose_name_plural': '\u7528\u6237\u5c5e\u6027',
            },
        ),
        migrations.CreateModel(
            name='WXUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=128, unique=True, verbose_name='openid')),
                ('nickname', models.CharField(blank=True, max_length=64, verbose_name='\u6635\u79f0')),
                ('sex', models.CharField(blank=True, max_length=10, verbose_name='\u6027\u522b')),
                ('province', models.CharField(blank=True, max_length=64, verbose_name='\u7701\u4efd')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='\u57ce\u5e02')),
                ('country', models.CharField(blank=True, max_length=64, verbose_name='\u56fd\u5bb6')),
                ('headimgurl', models.CharField(blank=True, max_length=512, verbose_name='\u5934\u50cf')),
                ('unionid', models.CharField(blank=True, max_length=128, verbose_name='unionid')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wx_user',
                'verbose_name': '\u5fae\u4fe1\u7528\u6237',
                'verbose_name_plural': '\u5fae\u4fe1\u7528\u6237',
            },
        ),
    ]
